---
  - name: "Install packages"
    yum: name="{{ item }}" state=latest
    with_items:
     - mc
     - wget
     - net-tools
     - epel-release
     - unzip
  - name: "Set hostnames"
    hostname: name={{ inventory_hostname }}







